### PR TITLE
Add aci_rest_managed resource

### PR DESCRIPTION
**Pull request by danischm**
Add `aci_rest_managed` resource as an alternative to the existing `aci_rest` resource. This resource can only manage a single API object (no children), but is able to read the state and reconcile config drift.

### CODE REVIEW

**Comment by FrederikSuijs** [comment]
Go Daniel! This is what we are all waiting for :-)

**Comment by FrederikSuijs** [comment]
@danischm does this mean the MR will not happen? That would be unfortunate.

**Comment by lhercot** [comment]
> @danischm does this mean the MR will not happen? That would be unfortunate.

We are looking at generalizing some improvements that are specific to this ressource so it might take a bit more time but still working on it.

**Comment by lhercot** [comment]
Closing this PR as PR #781 is a superset of this PR with up to date code.

**Pull request closed without merging**
