### PR TITLE
[ignore] Golang module dependency upgrades

### PR DESCRIPTION
**Pull request by akinross**

### CODE REVIEW

**Review by gmicol — APPROVED** [review]
LGTM

**Review by shrsr — DISMISSED** [review]
LGTM

**Review by samiib — CHANGES_REQUESTED** [review]
Should we update the README? It just says "Go Latest Version". 
I think we should be specific and say "Go v1.21 or higher".
The reason is that we won't always be able to keep up to date with latest go versions.

**Comment by akinross** [comment]
> Should we update the README? It just says "Go Latest Version". I think we should be specific and say "Go v1.21 or higher". The reason is that we won't always be able to keep up do date with latest go versions.

We could also set these minimum requirements from CI or from the generator logic, this way it will always be updates accordingly.What do you think?

**Review by samiib — APPROVED** [review]
LGTM

**Review by lhercot — APPROVED** [review]
LGTM

**Pull request merged**
