### PR TITLE
[bugfix] Allow import where an semicolon is part of the dn for ipv6 address

### PR DESCRIPTION
**Pull request by akinross**
#1189

### CODE REVIEW

**Comment by shrsr** [comment]
Will we have the same issue while importing other resources that contains IPv6 address?
Shall we incorporate this fix for all?

**Review by shrsr — COMMENTED** [review]
Will we have the same issue while importing other resources that contains IPv6 address?
Shall we incorporate this fix for all?

**Review by shrsr — APPROVED** [review]
LGTM
@akinross clarified my question with this: "not relevant for other resources because there we do not provide : as a separator"

**Review by shrsr — APPROVED** [review]
LGTM

**Review by samiib — APPROVED** [review]
LGTM

**Review by anvitha-jain — APPROVED** [review]

**Review by lhercot — APPROVED** [review]
LGTM

**Pull request merged**
