### PR TITLE
Removed check to test resource attributes when ImportStateVerify is set to true in resource tests

### PR DESCRIPTION
**Pull request by shrsr**

### CODE REVIEW

**Comment by samiib** [comment]
Sorry maybe a silly question but just wondering, why we needed to remove the attribute checks when ImportStateVerify is true?

**Comment by shrsr** [comment]
@samiib When ImportStateVerify is set to True, Terraform automatically verifies that the state of the imported resource matches the expected state.
The steps in the Check are ignored when the above field is True.

**Review by samiib — APPROVED** [review]
Awesome! Sounds good to me. 
LGTM!

**Review by akinross — APPROVED** [review]
LGTM

**Review by anvitha-jain — APPROVED** [review]

**Review by gmicol — APPROVED** [review]
LGTM

**Review by lhercot — APPROVED** [review]
LGTM

**Pull request merged**
